import { Roboto } from "next/font/google";
import Header from "./_components/header/Header";
import "./globals.css";
import Image from "next/image";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.className} antialiased`}>
      <body className=" flex flex-col h-screen">
        <header className="w-full">
          <Header />
        </header>
        <main className=" flex-1 w-full bg-gray-200 mb-2 rounded-xl max-w-[97.5%] mx-auto overflow-hidden">
          <div className=" h-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
